version: '3'
services:
  backhealth-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '10039:3000'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - /home/ubuntu/yetix/dashboard/upload-prod:/usr/api/upload
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
