version: '3'
services:
  backhealth-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '10035:3000'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
